# Generated by Django 2.2.3 on 2019-07-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField()),
                ('data_value', models.IntegerField()),
                ('data_type', models.CharField(max_length=45)),
                ('data_from', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'hackathon',
                'managed': False,
            },
        ),
    ]
